---
- hosts: "{{ host_identifier }}"
  user: admin
  become: root
  gather_facts: false
  tasks:
    - name: Install dVault
      dservice:
        state: latest
        name: dvault
        image: drunner/dvault
        install_config:
          - dvault configure
        out_port:
          - 8200
      environment:
        VAULT_ADDR: "{{ vault_addr }}"
        VAULT_TOKEN: "{{ vault_token }}"
        VAULT_CONTEXT: "{{ vault_context }}"
