version: '2'

services:
   dvault:
      image: drunner/dvault
      environment:
         - VAULT_ADDR
         - VAULT_TOKEN
         - VAULT_CONTEXT
      volumes:
         - "drunner-config:/config"
      network_mode: "bridge"

   dvault-loadpath:
      image: drunner/dvault
      environment:
         - VAULT_ADDR
         - VAULT_TOKEN
         - VAULT_CONTEXT
      volumes:
         - "drunner-config:/config"
         - "${LOAD_PATH}:/load"
      network_mode: "bridge"

   dvault-loadvolume:
      image: drunner/dvault
      environment:
         - VAULT_ADDR
         - VAULT_TOKEN
         - VAULT_CONTEXT
      volumes:
         - "drunner-config:/config"
         - "load:/load"
      network_mode: "bridge"

volumes:
   drunner-config:
      external:
         name: "drunner-${SERVICENAME}-config"
   # 'load' is not managed by drunner.  Used to load in another services volume
   load:
      external:
         name: "${LOAD_VOLUME}"
         