version: '2'

# we manage services manually in servicerunner, so there's no services
# section.

# if we don't want to use dRunner's environment variables for our
# configuraiton we should reinstate the config volume with this.
#volumes:
#   config:
#      external:
#         name: "drunner-${SERVICENAME}-config"
